[workspace]
resolver = "3"
members = [
    "frontend",
    "codegen",
    "core-tt",
    "core-tt/core-tt-macros",
    "core-tt/fuzz",
    "more-tt",
    "parser",
    "small-bit-vec",
    "small-bit-vec/fuzz",
    "typecheck",
    "debug", "inference",
]

